name: flutter_deer
description: Flutter Deer

version: 1.1.6+16
author: 唯鹿 <a05111993@163.com>
homepage: https://weilu.blog.csdn.net/

publish_to: 'none'

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Localization https://github.com/dart-lang/intl
  intl: ^0.17.0
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.0.0
  # 网络库 https://github.com/flutterchina/dio
  dio: ^4.0.0
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.25.0
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: 1.2.4
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^0.3.3
  # Flutter 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6  # flutter_swiper很久不维护，备用空安全版本：flutter_card_swiper: ^0.4.0
  # 启动URL的插件（支持Web） https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 6.0.3
  # 图片选择插件（支持Web） https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: 0.7.4
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.5.7
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 2.0.2
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.4.0
  # 列表悬浮头 https://github.com/fluttercommunity/flutter_sticky_headers
  sticky_headers: ^0.2.0
  # 城市选择列表 https://github.com/flutterchina/azlistview
  azlistview: ^1.1.1
  # 手势识别 https://github.com/aleksanderwozniak/simple_gesture_detector
  # simple_gesture_detector: ^0.1.4
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^2.0.3
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.5.1
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^6.0.0
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^5.0.0
  # 扫码 https://github.com/juliuscanute/qr_code_scanner
  qr_code_scanner: 0.4.0
  # App Shortcuts https://github.com/flutter/plugins/tree/master/packages/quick_actions
  quick_actions: 0.6.0
  # 刮刮卡 https://github.com/vintage/scratcher
  scratcher: ^2.0.1
  # 振动（支持Web） https://github.com/benjamindean/flutter_vibration
  vibration: ^1.7.3
  # 获取当前设备信息 https://github.com/flutter/plugins/tree/master/packages/device_info
  device_info: 2.0.0
  # 高德2D地图插件（支持Web） https://github.com/simplezhli/flutter_2d_amap
  flutter_2d_amap:
    git:
      ref: 'fdf1e412'
      url: 'https://github.com/simplezhli/flutter_2d_amap.git'

dev_dependencies:
  # Widget测试
  flutter_test:
    sdk: flutter
  # 集成测试
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  # 黄金测试
#  flutter_goldens:
#    sdk: flutter
  # 单元测试
  test: ^1.16.5

# For information on the generic Dart part of this file, see the
# following page: https:/w.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/home/
    - assets/images/store/
    - assets/images/state/
    - assets/images/order/
    - assets/images/order/dark/
    - assets/images/login/
    - assets/images/goods/
    - assets/images/shop/
    - assets/images/account/
    - assets/images/statistic/
    
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoThin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
